/* SPDX-License-Identifier: BSD-3-Clause */
/* stdlib_boot.h — stdlib bootstrap entry point.
 *
 * Registers the nine Object root C-native methods on the realm-global
 * Object proto, then loads the full stdlib (atom proto methods +
 * container internals + .u overlay blob).
 *
 * Per spec §5.2 boot order: stdlib boot runs AFTER urbi_native_protos_init
 * (Tag, Event natives) and BEFORE realm-globals populate.  At Phase 3 the
 * call site is inside urbi_populate_realm_globals immediately after the
 * idempotent urbi_native_protos_init guard, so the Object proto's
 * methods are visible the moment "Object" is installed as a realm
 * global. */

#ifndef URBI_STDLIB_BOOT_H
#define URBI_STDLIB_BOOT_H

#include <stddef.h>  /* size_t */

#ifdef __cplusplus
extern "C" {
#endif

struct UVM;

/* Returns URBI_OK on success or URBI_ERR_OOM on allocation failure.
 * Idempotent: subsequent calls are silent no-ops once vm->stdlib_booted
 * is set. */
int urbi_stdlib_boot(struct UVM *vm);

/* Baked stdlib bytecode blob.
 *
 * Generated by tools/urbi-compile-stdlib at host build time by walking
 * src/stdlib/STDLIB_ORDER.txt, compiling each .u to v1.5 bytecode, and
 * concatenating the resulting buffers into a single byte array.  Empty
 * (urbi_stdlib_bytecode_len == 0) until Phase 10 populates the order
 * file.  When non-empty, urbi_stdlib_boot deserializes the blob into a
 * heap-allocated UModule stored on vm->stdlib_module, then binds a
 * per-VM UChunkInstance via urbi_get_or_create_chunk_instance.  Phase
 * 4's empty-blob baseline never reaches the deserialize path. */
extern const unsigned char urbi_stdlib_bytecode[];
extern const size_t        urbi_stdlib_bytecode_len;

#ifdef __cplusplus
}
#endif

#endif /* URBI_STDLIB_BOOT_H */
