/* AUTO-GENERATED by tools/urbi-compile-stdlib. Do not edit.
 *
 * The baked form of src/stdlib/stdlib.u: one chunk, deserialized and run
 * once per VM by uboot_init with recv = root_globals, so its top-level
 * declarations land as slots on the object every realm inherits from.
 *
 * Empty while the overlay is being rewritten against the re-founded core.
 */

#include <stddef.h>

const unsigned char urbi_stdlib_bytecode[1] = {
    0
};

const size_t urbi_stdlib_bytecode_len = 0;
