/* AUTO-GENERATED by tools/urbi-compile-stdlib. Do not edit.
 *
 * Build-time output: walks src/stdlib/STDLIB_ORDER.txt, compiles
 * each .u to bytecode via urbi_compile_source, concatenates the
 * resulting v1.5 wire-format buffers, emits this file.
 *
 * Empty placeholder until Phase 10 populates STDLIB_ORDER.txt.
 */

#include <stddef.h>

const unsigned char urbi_stdlib_bytecode[1] = { 0 };
const size_t urbi_stdlib_bytecode_len = 0;
