/* SPDX-License-Identifier: BSD-3-Clause */
/* uopcode_shape.c — opcode-shape table data.  See uopcode_shape.h. */

#include "uopcode_shape.h"
#include "urbi/types.h"   /* URBI_STATIC_ASSERT */

/* Pin the row count against the .def so a new opcode in the enum without a
 * matching shape entry causes a compile-time error. */
URBI_STATIC_ASSERT(OP_MAX == 41, "uopcodes.def row count diverged from shape table");

const UOpcodeShape urbi_opcode_shapes[OP_MAX] = {
    [OP_LOADK]    = { UOPF_ABX, UOPK_REG,    UOPK_UNUSED, UOPK_UNUSED,   UBXK_POOL_INDEX },
    [OP_MOVE]     = { UOPF_ABC, UOPK_REG,    UOPK_REG,    UOPK_UNUSED,   UBXK_UNUSED },
    [OP_ADD]      = { UOPF_ABC, UOPK_REG,    UOPK_REG,    UOPK_REG,      UBXK_UNUSED },
    [OP_SUB]      = { UOPF_ABC, UOPK_REG,    UOPK_REG,    UOPK_REG,      UBXK_UNUSED },
    [OP_MUL]      = { UOPF_ABC, UOPK_REG,    UOPK_REG,    UOPK_REG,      UBXK_UNUSED },
    [OP_DIV]      = { UOPF_ABC, UOPK_REG,    UOPK_REG,    UOPK_REG,      UBXK_UNUSED },
    [OP_NEG]      = { UOPF_ABC, UOPK_REG,    UOPK_REG,    UOPK_UNUSED,   UBXK_UNUSED },
    [OP_RET]      = { UOPF_ABC, UOPK_REG,    UOPK_UNUSED, UOPK_UNUSED,   UBXK_UNUSED },
    [OP_LOADNIL]  = { UOPF_ABC, UOPK_REG,    UOPK_UNUSED, UOPK_UNUSED,   UBXK_UNUSED },
    [OP_LOADBOOL] = { UOPF_ABC, UOPK_REG,    UOPK_IMM_BOOL, UOPK_IMM_BOOL, UBXK_UNUSED },
    [OP_LOADVOID] = { UOPF_ABC, UOPK_REG,    UOPK_UNUSED, UOPK_UNUSED,   UBXK_UNUSED },
    [OP_GETUPVAL] = { UOPF_ABC, UOPK_REG,    UOPK_UPVAL_IDX, UOPK_UNUSED, UBXK_UNUSED },
    [OP_SETUPVAL] = { UOPF_ABC, UOPK_REG,    UOPK_UPVAL_IDX, UOPK_UNUSED, UBXK_UNUSED },
    [OP_CLOSURE]  = { UOPF_ABX, UOPK_REG,    UOPK_UNUSED, UOPK_UNUSED,   UBXK_NESTED_INDEX },
    [OP_CLOSE]    = { UOPF_ABC, UOPK_REG,    UOPK_UNUSED, UOPK_UNUSED,   UBXK_UNUSED },
    [OP_CALL]     = { UOPF_ABC, UOPK_REG,    UOPK_REG,    UOPK_UNUSED,   UBXK_UNUSED },
    [OP_JMP]      = { UOPF_ABX, UOPK_UNUSED, UOPK_UNUSED, UOPK_UNUSED,   UBXK_JUMP_SIGNED },
    [OP_TEST]     = { UOPF_ABC, UOPK_REG,    UOPK_UNUSED, UOPK_IMM_BOOL, UBXK_UNUSED },
    [OP_TESTSET]  = { UOPF_ABC, UOPK_REG,    UOPK_REG,    UOPK_IMM_BOOL, UBXK_UNUSED },
    [OP_EQ]       = { UOPF_ABC, UOPK_IMM_BOOL, UOPK_REG,  UOPK_REG,      UBXK_UNUSED },
    [OP_LT]       = { UOPF_ABC, UOPK_IMM_BOOL, UOPK_REG,  UOPK_REG,      UBXK_UNUSED },
    [OP_LE]       = { UOPF_ABC, UOPK_IMM_BOOL, UOPK_REG,  UOPK_REG,      UBXK_UNUSED },
    [OP_YIELD]    = { UOPF_ABC, UOPK_UNUSED, UOPK_UNUSED, UOPK_UNUSED,   UBXK_UNUSED },
    [OP_FORK]     = { UOPF_ABC, UOPK_REG,    UOPK_REG_OR_NONE, UOPK_IMM_BOOL, UBXK_UNUSED },
    [OP_JOIN_WAIT]= { UOPF_ABC, UOPK_REG,    UOPK_UNUSED, UOPK_UNUSED,   UBXK_UNUSED },
    [OP_GETSLOT]  = { UOPF_ABC, UOPK_REG,    UOPK_REG,    UOPK_IMM_SITE, UBXK_UNUSED },
    [OP_SETSLOT]  = { UOPF_ABC, UOPK_REG,    UOPK_REG,    UOPK_IMM_SITE, UBXK_UNUSED },
    [OP_SETSLOT_UPDATE] = { UOPF_ABC, UOPK_REG, UOPK_REG, UOPK_IMM_SITE, UBXK_UNUSED },
    [OP_SELF]     = { UOPF_ABC, UOPK_REG,    UOPK_REG,    UOPK_IMM_SITE, UBXK_UNUSED },
    [OP_GETSLOT_CHANGE_EVENT] = { UOPF_ABC, UOPK_REG, UOPK_REG, UOPK_IMM_SITE, UBXK_UNUSED },
    [OP_EXTARG]   = { UOPF_ABX, UOPK_UNUSED, UOPK_UNUSED, UOPK_UNUSED,   UBXK_EXTARG },
    [OP_THROW]    = { UOPF_ABC, UOPK_REG,    UOPK_UNUSED, UOPK_UNUSED,   UBXK_UNUSED },
    [OP_SCOPE_TRY]= { UOPF_ABX, UOPK_IMM_FLAGS, UOPK_UNUSED, UOPK_UNUSED, UBXK_HANDLER_PC },
    [OP_SCOPE_TAG]= { UOPF_ABX, UOPK_REG_OR_NONE, UOPK_UNUSED, UOPK_UNUSED, UBXK_HANDLER_PC },
    [OP_SCOPE_POP]= { UOPF_ABC, UOPK_IMM_FLAGS, UOPK_UNUSED, UOPK_UNUSED, UBXK_UNUSED },
    [OP_UNWIND_TO]= { UOPF_ABX, UOPK_IMM_DEPTH, UOPK_UNUSED, UOPK_UNUSED, UBXK_HANDLER_PC },
    [OP_RESUME]   = { UOPF_ABC, UOPK_UNUSED, UOPK_UNUSED, UOPK_UNUSED,   UBXK_UNUSED },
    [OP_LOAD_CATCH_VALUE] = { UOPF_ABC, UOPK_REG, UOPK_UNUSED, UOPK_UNUSED, UBXK_UNUSED },
    [OP_INSTALL]  = { UOPF_ABC, UOPK_REG,    UOPK_IMM_MODE, UOPK_IMM_FLAGS, UBXK_UNUSED },
    [OP_LOAD_REALM_GLOBAL] = { UOPF_ABC, UOPK_REG, UOPK_UNUSED, UOPK_UNUSED, UBXK_UNUSED },
    [OP_LOAD_RECV]= { UOPF_ABC, UOPK_REG,    UOPK_UNUSED, UOPK_UNUSED,   UBXK_UNUSED },
};
