/* SPDX-License-Identifier: BSD-3-Clause */
/* Mandelbrot demo for STM32F429I-DISC1.
 *
 * Bare-metal init: HAL clocks at 180 MHz, SDRAM, LCD, gyro, UART, button GPIO.
 * Then drops into the urbi event pump: load baked bytecode, urbi_step loop
 * with WFI sleep when QUIESCENT, SystemReset on FATAL.
 *
 * NOTE (Task 19): Several urbi API call sites below use the signatures from
 * the task spec and may not match the shipped API exactly.  Task 21 is the
 * first compile attempt; mismatches will be reconciled there.  Known
 * discrepancies flagged inline with "FIXME(T21):" comments:
 *   - urbi_vm_alloc does not exist; UVM is stack/static + urbi_vm_init(vm, alloc, ud)
 *   - urbi_run_chunk takes (vm, realm, module, *out_result), not raw bytes
 *   - urbi_register takes (vm, realm, name, fn), not (vm, name, fn, nargs)
 *   - urbi_event_register takes (vm, realm, name, destruct_fn, destruct_ud)
 *   - UStepStatus -> UStepResult; enum prefix URBI_STEP_* matches the actual names
 *   - urbi_step takes (vm, budget, *out_next_wake_us) — 3 args
 *   - mandelbrot_baked.h symbol name / include TBD (Task 20 generates it) */

#include "stm32f4xx_hal.h"
#include "stm32f429i_discovery.h"
#include "stm32f429i_discovery_sdram.h"
#include "stm32f429i_discovery_lcd.h"
#include "stm32f429i_discovery_gyroscope.h"
#include <string.h>
#include "port_stm32f4.h"
#include "urbi/urbi.h"
#include "urbi/types.h"
#include "mandelbrot_baked.h"   /* generated by tools/urbi-compile-stdlib --to-header */

UART_HandleTypeDef huart1;   /* defined here; port_writer.c uses extern */

/* DWT enable — needed by port_time.c for DWT->CYCCNT access. */
static void dwt_enable(void) {
    CoreDebug->DEMCR |= CoreDebug_DEMCR_TRCENA_Msk;
    DWT->CYCCNT = 0;
    DWT->CTRL |= DWT_CTRL_CYCCNTENA_Msk;
}

/* 180 MHz clock config — copy/adapt from STM32CubeF4 Templates main.c. */
static void SystemClock_Config(void) {
    RCC_OscInitTypeDef osc = {0};
    RCC_ClkInitTypeDef clk = {0};

    __HAL_RCC_PWR_CLK_ENABLE();
    __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE1);

    osc.OscillatorType = RCC_OSCILLATORTYPE_HSE;
    osc.HSEState = RCC_HSE_ON;
    osc.PLL.PLLState = RCC_PLL_ON;
    osc.PLL.PLLSource = RCC_PLLSOURCE_HSE;
    osc.PLL.PLLM = 8;
    osc.PLL.PLLN = 360;
    osc.PLL.PLLP = RCC_PLLP_DIV2;
    osc.PLL.PLLQ = 7;
    if (HAL_RCC_OscConfig(&osc) != HAL_OK) while (1);

    if (HAL_PWREx_EnableOverDrive() != HAL_OK) while (1);

    clk.ClockType = RCC_CLOCKTYPE_HCLK | RCC_CLOCKTYPE_SYSCLK |
                    RCC_CLOCKTYPE_PCLK1 | RCC_CLOCKTYPE_PCLK2;
    clk.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
    clk.AHBCLKDivider = RCC_SYSCLK_DIV1;
    clk.APB1CLKDivider = RCC_HCLK_DIV4;
    clk.APB2CLKDivider = RCC_HCLK_DIV2;
    if (HAL_RCC_ClockConfig(&clk, FLASH_LATENCY_5) != HAL_OK) while (1);
}

int main(void) {
    HAL_Init();
    SystemClock_Config();
    dwt_enable();

    BSP_SDRAM_Init();
    port_lcd_init();
    port_gyro_init();
    port_uart_init();
    port_button_init_gpio();

    /* Splash */
    BSP_LCD_Clear(LCD_COLOR_BLACK);
    BSP_LCD_SetTextColor(LCD_COLOR_WHITE);
    BSP_LCD_SetBackColor(LCD_COLOR_BLACK);
    BSP_LCD_SetFont(&Font12);
    BSP_LCD_DisplayStringAtLine(0, (uint8_t *)"urbi v0.8.2-stm32f4-mandelbrot");

    /* Hello UART */
    const char *hello = "urbi v0.8.2-stm32f4-mandelbrot booting\r\n";
    HAL_UART_Transmit(&huart1, (const uint8_t *)hello, strlen(hello), 100);

    /* Stand up the VM.
     * FIXME(T21): urbi_vm_alloc does not exist in the shipped API.
     * Correct pattern: declare a static UVM (needs internal uvm.h for sizeof),
     * or use the hosted malloc path.  Reconcile at first compile attempt. */
    UVM *vm = urbi_vm_alloc(port_alloc, NULL);
    if (urbi_vm_init(vm) != 0) {
        const char *err = "urbi_vm_init FAILED\r\n";
        HAL_UART_Transmit(&huart1, (const uint8_t *)err, strlen(err), 100);
        while (1);
    }
    urbi_set_writer(vm, port_writer, NULL);
    urbi_set_time_us(vm, port_time_us);
    urbi_set_diag_fn(vm, port_diag);
    urbi_set_isr_check_fn(vm, port_in_isr);

    /* Register host-fns.
     * FIXME(T21): urbi_register signature is (vm, realm, name, fn) — realm arg
     * is missing here.  Pass NULL realm to use the VM's global realm. */
    urbi_register(vm, "lcd_fill_rect", port_lcd_fill_rect_native, 5);
    urbi_register(vm, "gyro_x",        port_gyro_x_native,        0);
    urbi_register(vm, "gyro_y",        port_gyro_y_native,        0);
    urbi_register(vm, "gyro_z",        port_gyro_z_native,        0);

    /* Register the button event and bind to EXTI ISR.
     * FIXME(T21): urbi_event_register signature is
     * (vm, realm, name, destruct_fn, destruct_ud) — adjust at T21. */
    uint32_t button_evt = urbi_event_register(vm, "button_press");
    port_button_init(vm, button_evt);

    /* Load baked bytecode.
     * FIXME(T21): urbi_run_chunk signature is (vm, realm, module, *out_result).
     * mandelbrot_bytecode/len are the expected symbol names from the baked header
     * (exact names depend on --symbol arg to urbi-compile-stdlib; Task 20 sets
     * those).  Switch to urbi_module_from_bytes + urbi_run_chunk at T21. */
    if (urbi_run_chunk(vm, mandelbrot_bytecode, mandelbrot_bytecode_len, 0) != 0) {
        const char *err = "urbi_run_chunk FAILED\r\n";
        HAL_UART_Transmit(&huart1, (const uint8_t *)err, strlen(err), 100);
        while (1);
    }

    /* Event pump.
     * FIXME(T21): urbi_step signature is (vm, budget_instructions, *out_next_wake_us).
     * The third arg (uint64_t *out_next_wake_us) is missing below — pass NULL. */
    while (1) {
        UStepResult st = urbi_step(vm, 256);
        switch (st) {
            case URBI_STEP_RUNNING:
                break;
            case URBI_STEP_QUIESCENT:
            case URBI_STEP_WAKE_AT:
                __WFI();
                break;
            case URBI_STEP_FATAL:
                NVIC_SystemReset();
                break;
            default:
                break;
        }
    }
}
