/* SPDX-License-Identifier: BSD-3-Clause */
/* tools/urbi-compile-stdlib.c
 *
 * Build-time tool: walk STDLIB_ORDER.txt, compile each .u to bytecode
 * via the public Urbi compile API, emit src/stdlib/urbi_stdlib_bytecode.gen.c.
 *
 * Two-pass build (per delta spec §3.1):
 *   1. liburbi.a builds with placeholder .gen.c (0-length blob)
 *   2. tools/urbi-compile-stdlib runs against that intermediate library
 *   3. liburbi.a re-links with the populated .gen.c
 *
 * Phase 3 baseline: walks the order file but does NOT actually compile —
 * empty STDLIB_ORDER.txt produces a 0-length blob. Phase 10 fills in the
 * urbi_compile_source loop once the public compile API and the .u files
 * are in place. */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "urbi/urbi.h"
#include "urbi/types.h"

#define MAX_LINE        256
#define MAX_BLOB_BYTES  (256 * 1024)   /* 256 KB cap for stdlib blob */

/* Emit the .gen.c file: header comment, byte array, length variable.
 * Output format must be byte-stable for the determinism smoke gate
 * (tests/scripts/bake_smoke.sh): no timestamps, no input-path strings,
 * no PID-derived markers. */
static void
emit_c_array(FILE *out, const unsigned char *blob, size_t blob_len)
{
    fprintf(out,
        "/* AUTO-GENERATED by tools/urbi-compile-stdlib. Do not edit.\n"
        " *\n"
        " * Build-time output: walks src/stdlib/STDLIB_ORDER.txt, compiles\n"
        " * each .u to bytecode via the public compile API, concatenates the\n"
        " * resulting v1.5 wire-format buffers, emits this file.\n"
        " *\n"
        " * Empty placeholder until Phase 10 populates STDLIB_ORDER.txt.\n"
        " */\n"
        "\n"
        "#include <stddef.h>\n"
        "\n"
        "const unsigned char urbi_stdlib_bytecode[%zu] = {\n",
        blob_len ? blob_len : (size_t)1);

    if (blob_len == 0) {
        fprintf(out, "    0\n");
    } else {
        for (size_t i = 0; i < blob_len; i++) {
            if (i % 16 == 0) fprintf(out, "    ");
            fprintf(out, "0x%02X,", blob[i]);
            if ((i + 1) % 16 == 0 || i + 1 == blob_len) {
                fprintf(out, "\n");
            } else {
                fprintf(out, " ");
            }
        }
    }
    fprintf(out,
        "};\n"
        "\n"
        "const size_t urbi_stdlib_bytecode_len = %zu;\n",
        blob_len);
}

int
main(int argc, char **argv)
{
    if (argc != 4) {
        fprintf(stderr,
            "usage: %s STDLIB_ORDER.txt SRC_DIR OUTPUT.gen.c\n",
            argv[0]);
        return 2;
    }
    const char *order_path = argv[1];
    const char *src_dir    = argv[2];
    const char *out_path   = argv[3];

    FILE *order = fopen(order_path, "r");
    if (!order) {
        fprintf(stderr, "[bake] cannot open %s\n", order_path);
        return 1;
    }

    unsigned char *blob = malloc(MAX_BLOB_BYTES);
    if (!blob) {
        fclose(order);
        fprintf(stderr, "[bake] OOM allocating blob buffer\n");
        return 1;
    }
    size_t blob_len = 0;

    /* Phase 10 fills the actual compile loop here. Phase 3 ships the
     * scaffold with an empty walk that produces a 0-length blob.
     * Each non-blank line is the basename of a .u file under src_dir. */
    char line[MAX_LINE];
    while (fgets(line, sizeof line, order)) {
        size_t n = strlen(line);
        while (n && (line[n - 1] == '\n' || line[n - 1] == '\r')) {
            line[--n] = 0;
        }
        if (n == 0) continue;            /* blank line */
        if (line[0] == '#') continue;    /* comment */

        /* TODO Phase 10: read src_dir/line, compile via urbi_compile_source,
         * append bytecode to blob (length-prefixed if needed by the runtime
         * loader, or topologically ordered concat if accepted by
         * urbi_module_load directly). */
        fprintf(stderr,
            "[bake] would compile %s/%s (Phase 10)\n",
            src_dir, line);
    }
    fclose(order);

    FILE *out = fopen(out_path, "w");
    if (!out) {
        free(blob);
        fprintf(stderr, "[bake] cannot open %s for writing\n", out_path);
        return 1;
    }
    emit_c_array(out, blob, blob_len);
    fclose(out);
    free(blob);

    fprintf(stderr, "[bake] wrote %s (%zu bytes blob)\n", out_path, blob_len);
    return 0;
}
