#!/usr/bin/env python3
"""urbi-rosgen.py — emit self-contained C structs + marshal/unmarshal + a
type registry for a fixed message manifest. v0.12.1: scalar + nested-scalar
+ string + sequence (mock-path, fixed-cap).
Usage: urbi-rosgen.py <manifest.json> <out.gen.c> <out.gen.h>"""
import json, sys, re

PRIM_C = {"bool": "uint8_t", "uint8": "uint8_t", "int32": "int32_t",
          "uint32": "uint32_t", "int64": "int64_t",
          "float32": "float", "float64": "double"}

SLOT_READ = {"bool": "urbi_value_as_bool", "uint8": "urbi_value_as_int",
             "int32": "urbi_value_as_int", "uint32": "urbi_value_as_int",
             "int64": "urbi_value_as_int",
             "float32": "urbi_value_as_float", "float64": "urbi_value_as_float"}
CCAST = {"bool": "(uint8_t)", "uint8": "(uint8_t)", "int32": "(int32_t)",
         "uint32": "(uint32_t)", "int64": "(int64_t)",
         "float32": "(float)", "float64": "(double)"}
MAKE = {"bool": "urbi_make_bool", "uint8": "urbi_make_int",
        "int32": "urbi_make_int", "uint32": "urbi_make_int",
        "int64": "urbi_make_int",
        "float32": "urbi_make_float", "float64": "urbi_make_float"}

# Fixed capacities for the mock-only self-contained struct representation.
# The rcl path (--target rcl, Phase B) uses unbounded rosidl heap fields.
MOCK_STRING_CAP = 256
MOCK_SEQ_CAP    = 64

def is_seq(ftype):
    """Return True if ftype is a sequence kind (e.g. 'float32[]')."""
    return ftype.endswith("[]")

def seq_elem(ftype):
    """Return the element type of a sequence field (e.g. 'float32[]' -> 'float32')."""
    return ftype[:-2]

def cident(type_name):
    return "urbi_ros__" + type_name.replace("/", "__")

def field_ctype(ftype):
    if ftype in PRIM_C:
        return PRIM_C[ftype]
    return "struct " + cident(ftype)   # nested message

def toposort(msgs):
    seen, order = set(), []
    def visit(n):
        if n in seen or n not in msgs: return
        for _, ft in msgs[n]:
            elem = seq_elem(ft) if is_seq(ft) else ft
            if elem not in PRIM_C and elem != "string": visit(elem)
        seen.add(n); order.append(n)
    for n in msgs: visit(n)
    return order

def emit_header(msgs):
    out = ["/* GENERATED by tools/urbi-rosgen.py - do not edit. */",
           "#ifndef UROS_MSGS_GEN_H", "#define UROS_MSGS_GEN_H",
           "#ifdef URBI_ENABLE_ROS2", "#include <stdint.h>",
           "#include <string.h>  /* memcpy / strncpy */", ""]
    for name in toposort(msgs):
        out.append("struct %s {" % cident(name))
        for fname, ftype in msgs[name]:
            if ftype == "string":
                # mock-only: fixed 256-byte buffer; rcl path uses rosidl String
                out.append("    char %s[%d]; /* mock-only fixed cap */" % (fname, MOCK_STRING_CAP))
            elif is_seq(ftype):
                elem = seq_elem(ftype)
                celem = PRIM_C[elem]  # sequences are always primitive at v0.12.1
                # mock-only: fixed 64-element array; rcl path uses rosidl Sequence
                out.append("    struct { %s data[%d]; uint32_t size; } %s; /* mock-only fixed cap */" % (
                    celem, MOCK_SEQ_CAP, fname))
            else:
                out.append("    %s %s;" % (field_ctype(ftype), fname))
        out.append("};")
        out.append("")
    out += ["#endif", "#endif", ""]
    return "\n".join(out)

def emit_forward_decls(msgs):
    out = []
    for name in toposort(msgs):
        cs, base = cident(name), name.replace("/", "__")
        out.append("int urbi_ros_marshal__%s(struct UVM *vm, UValue obj, struct %s *out);" % (base, cs))
        out.append("int urbi_ros_unmarshal__%s(struct UVM *vm, const struct %s *in, UValue *out);" % (base, cs))
    return "\n".join(out)

def emit_marshal(msgs):
    out = []
    for name in toposort(msgs):
        cs, fn = cident(name), "urbi_ros_marshal__" + name.replace("/", "__")
        out.append("int %s(struct UVM *vm, UValue obj, struct %s *out) {" % (fn, cs))
        for fname, ftype in msgs[name]:
            if ftype == "string":
                out.append('    { UValue _v = urbi_make_nil(); size_t _slen = 0;')
                out.append('      if (urbi_slot_get(vm, obj, "%s", %d, &_v) != 0) return -1;' % (fname, len(fname)))
                out.append('      { const char *_s = urbi_value_as_str(_v, &_slen);')
                out.append('        if (_s == NULL) { out->%s[0] = \'\\0\'; }' % fname)
                out.append('        else { strncpy(out->%s, _s, %d - 1U); out->%s[%d - 1] = \'\\0\'; } } }' % (
                    fname, MOCK_STRING_CAP, fname, MOCK_STRING_CAP))
            elif is_seq(ftype):
                elem = seq_elem(ftype)
                out.append('    { UValue _lst = urbi_make_nil(); int _n, _i;')
                out.append('      if (urbi_slot_get(vm, obj, "%s", %d, &_lst) != 0) return -1;' % (fname, len(fname)))
                out.append('      _n = urbi_list_len(vm, _lst);')
                out.append('      if (_n < 0) _n = 0;')
                out.append('      if (_n > %d) _n = %d;' % (MOCK_SEQ_CAP, MOCK_SEQ_CAP))
                out.append('      out->%s.size = (uint32_t)_n;' % fname)
                out.append('      for (_i = 0; _i < _n; _i++) {')
                out.append('        UValue _ev = urbi_list_get(vm, _lst, _i);')
                out.append('        out->%s.data[_i] = %s%s(_ev); } }' % (
                    fname, CCAST[elem], SLOT_READ[elem]))
            elif ftype in PRIM_C:
                out.append('    { UValue _v = urbi_make_nil();')
                out.append('      if (urbi_slot_get(vm, obj, "%s", %d, &_v) != 0) return -1;' % (fname, len(fname)))
                out.append('      out->%s = %s%s(_v); }' % (fname, CCAST[ftype], SLOT_READ[ftype]))
            else:
                nfn = "urbi_ros_marshal__" + ftype.replace("/", "__")
                out.append('    { UValue _v = urbi_make_nil();')
                out.append('      if (urbi_slot_get(vm, obj, "%s", %d, &_v) != 0) return -1;' % (fname, len(fname)))
                out.append('      if (%s(vm, _v, &out->%s) != 0) return -1; }' % (nfn, fname))
        out.append("    return 0;\n}")
    return "\n".join(out)

def emit_unmarshal(msgs):
    out = []
    for name in toposort(msgs):
        cs, fn = cident(name), "urbi_ros_unmarshal__" + name.replace("/", "__")
        out.append("int %s(struct UVM *vm, const struct %s *in, UValue *out) {" % (fn, cs))
        out.append('    struct UObject *o = urbi_ros_msg_alloc(vm, "%s");' % name)
        out.append("    if (o == NULL) return -1;")
        out.append("    UValue obj = urbi_make_object(o);")
        for fname, ftype in msgs[name]:
            if ftype == "string":
                out.append('    { size_t _slen = strlen(in->%s);' % fname)
                out.append('      UValue _sv = urbi_make_str_interned(vm, in->%s, _slen);' % fname)
                out.append('      if (urbi_slot_set(vm, obj, "%s", %d, _sv) != 0) return -1; }' % (fname, len(fname)))
            elif is_seq(ftype):
                elem = seq_elem(ftype)
                out.append('    { uint32_t _n = in->%s.size; uint32_t _i;' % fname)
                out.append('      UValue _lst = urbi_list_create(vm);')
                out.append('      if (_lst.kind == (uint8_t)UVAL_NIL) return -1;')
                out.append('      for (_i = 0; _i < _n && _i < %dU; _i++) {' % MOCK_SEQ_CAP)
                out.append('        if (urbi_list_append(vm, _lst, %s(in->%s.data[_i])) != 0) return -1; }' % (
                    MAKE[elem], fname))
                out.append('      if (urbi_slot_set(vm, obj, "%s", %d, _lst) != 0) return -1; }' % (fname, len(fname)))
            elif ftype in PRIM_C:
                out.append('    if (urbi_slot_set(vm, obj, "%s", %d, %s(in->%s)) != 0) return -1;' % (fname, len(fname), MAKE[ftype], fname))
            else:
                nfn = "urbi_ros_unmarshal__" + ftype.replace("/", "__")
                out.append('    { UValue _nv = urbi_make_nil();')
                out.append('      if (%s(vm, &in->%s, &_nv) != 0) return -1;' % (nfn, fname))
                out.append('      if (urbi_slot_set(vm, obj, "%s", %d, _nv) != 0) return -1; }' % (fname, len(fname)))
        out.append("    *out = obj; return 0;\n}")
    return "\n".join(out)

def emit_registry(msgs):
    order = toposort(msgs); out = []
    for name in order:
        base = name.replace("/", "__")
        out.append("static int _m_%s(struct UVM *vm, UValue o, void *p){return urbi_ros_marshal__%s(vm,o,(struct %s*)p);}" % (base, base, cident(name)))
        out.append("static int _u_%s(struct UVM *vm, const void *p, UValue *o){return urbi_ros_unmarshal__%s(vm,(const struct %s*)p,o);}" % (base, base, cident(name)))
    out.append("static const URosMsgType g_ros_types[] = {")
    for name in order:
        base = name.replace("/", "__")
        out.append('  { "%s", sizeof(struct %s), _m_%s, _u_%s },' % (name, cident(name), base, base))
    out.append("};")
    out.append("static const int g_ros_types_n = %d;" % len(order))
    out.append('const URosMsgType *urbi_ros_msg_lookup(const char *name){')
    out.append('  int i; for (i=0;i<g_ros_types_n;i++) if (urbi_streq(name, g_ros_types[i].name)) return &g_ros_types[i];')
    out.append('  return 0;\n}')
    out.append("int urbi_ros_msg_register_all(struct UVM *vm){")
    out.append("  if (vm == 0 || vm->ros_proto == 0) return -1;")
    out.append("  urbi_ros_msg__reset();")
    for name in order:
        slot = "msg__" + name.replace("/", "__")
        out.append('  { struct UObject *o = urbi_object_clone(vm, urbi_object_root(vm)); if(!o) return -1;')
        for fname, ftype in msgs[name]:
            out.append('    if (urbi_slot_set(vm, urbi_make_object(o), "%s", %d, urbi_make_nil())!=0) return -1;' % (fname, len(fname)))
        out.append('    urbi_ros_msg__record(vm, "%s", o);' % name)
        out.append('    { USymbol *sy=(USymbol*)ustr_intern(vm,"%s",%d); if(!sy) return -1; urbi_object_set_local_slot(vm,(struct UObject*)vm->ros_proto,sy,urbi_make_object(o)); } }' % (slot, len(slot)))
    out.append("  return 0;\n}")
    return "\n".join(out)

def emit_c(msgs):
    parts = [
        "/* GENERATED by tools/urbi-rosgen.py - do not edit. */",
        "#ifdef URBI_ENABLE_ROS2",
        "#include <string.h>  /* strlen / strncpy */",
        '#include "urbi/urbi.h"',
        '#include "urbi/types.h"',
        '#include "vm/uvm.h"',
        '#include "object/uobject.h"',
        '#include "value/uintern.h"',
        '#include "value/ulist_build.h"',
        '#include "ros/uros_msg.h"',
        '#include "ros/generated/ros_msgs.gen.h"',
        "",
        "/* Forward declarations: nested-message marshal/unmarshal are called",
        " * by reference before their definitions in toposort order. */",
        emit_forward_decls(msgs),
        "",
        emit_marshal(msgs),
        "",
        emit_unmarshal(msgs),
        "",
        emit_registry(msgs),
        "",
        "#else",
        "typedef int uros_translation_unit_not_empty;",
        "#endif /* URBI_ENABLE_ROS2 */",
        "",
    ]
    return "\n".join(parts)

# ===========================================================================
# --target rcl : marshal/unmarshal against the real rosidl-generated structs.
# Unlike the mock path, the C structs come from the rosidl headers (we do NOT
# emit struct definitions); we emit marshal/unmarshal + typesupport accessors +
# a name-keyed registry.  Generated in-container only (needs rosidl headers).
# ===========================================================================

# rosidl sequence struct names: rosidl_runtime_c__<elem>__Sequence
RCL_SEQ_ELEM = {"float32": "float", "float64": "double", "uint8": "uint8",
                "int32": "int32", "uint32": "uint32",
                "int64": "int64", "bool": "boolean"}

def snake(name):
    """CamelCase -> snake_case (ROS header-file convention)."""
    s1 = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', name)
    return re.sub('([a-z0-9])([A-Z])', r'\1_\2', s1).lower()

def is_srv_part(typ):
    return typ.endswith("_Request") or typ.endswith("_Response")

def rcl_parts(name):
    """(pkg, typ, interface, rcl_struct, header) for a manifest type name."""
    pkg, typ = name.split("/")
    if is_srv_part(typ):
        base = typ.rsplit("_", 1)[0]            # AddTwoInts_Request -> AddTwoInts
        return (pkg, typ, "srv", "%s__srv__%s" % (pkg, typ),
                "%s/srv/%s.h" % (pkg, snake(base)))
    return (pkg, typ, "msg", "%s__msg__%s" % (pkg, typ),
            "%s/msg/%s.h" % (pkg, snake(typ)))

def emit_rcl_marshal_field(fname, ftype):
    flen = len(fname)
    if ftype == "string":
        return [
          '    { UValue _v = urbi_make_nil(); size_t _sl = 0;',
          '      if (urbi_slot_get(vm, obj, "%s", %d, &_v) != 0) return -1;' % (fname, flen),
          '      { const char *_s = urbi_value_as_str(_v, &_sl);',
          '        if (!rosidl_runtime_c__String__assignn(&out->%s, _s ? _s : "", _s ? _sl : 0)) return -1; } }' % fname,
        ]
    if is_seq(ftype):
        elem = seq_elem(ftype); sq = RCL_SEQ_ELEM[elem]
        return [
          '    { UValue _lst = urbi_make_nil(); int _n, _i;',
          '      if (urbi_slot_get(vm, obj, "%s", %d, &_lst) != 0) return -1;' % (fname, flen),
          '      _n = urbi_list_len(vm, _lst); if (_n < 0) _n = 0;',
          '      rosidl_runtime_c__%s__Sequence__fini(&out->%s);' % (sq, fname),
          '      if (!rosidl_runtime_c__%s__Sequence__init(&out->%s, (size_t)_n)) return -1;' % (sq, fname),
          '      for (_i = 0; _i < _n; _i++) {',
          '        UValue _ev = urbi_list_get(vm, _lst, _i);',
          '        out->%s.data[_i] = %s%s(_ev); } }' % (fname, CCAST[elem], SLOT_READ[elem]),
        ]
    if ftype in PRIM_C:
        return [
          '    { UValue _v = urbi_make_nil();',
          '      if (urbi_slot_get(vm, obj, "%s", %d, &_v) != 0) return -1;' % (fname, flen),
          '      out->%s = %s%s(_v); }' % (fname, CCAST[ftype], SLOT_READ[ftype]),
        ]
    nfn = "urbi_ros_marshal_rcl__" + ftype.replace("/", "__")
    return [
      '    { UValue _v = urbi_make_nil();',
      '      if (urbi_slot_get(vm, obj, "%s", %d, &_v) != 0) return -1;' % (fname, flen),
      '      if (%s(vm, _v, &out->%s) != 0) return -1; }' % (nfn, fname),
    ]

def emit_rcl_unmarshal_field(fname, ftype):
    flen = len(fname)
    if ftype == "string":
        return [
          '    { UValue _sv = urbi_make_str_interned(vm, in->%s.data ? in->%s.data : "", in->%s.size);' % (fname, fname, fname),
          '      if (_sv.kind == (uint8_t)UVAL_NIL) return -1;',
          '      if (urbi_slot_set(vm, obj, "%s", %d, _sv) != 0) return -1; }' % (fname, flen),
        ]
    if is_seq(ftype):
        elem = seq_elem(ftype)
        return [
          '    { size_t _i; UValue _lst = urbi_list_create(vm);',
          '      if (_lst.kind == (uint8_t)UVAL_NIL) return -1;',
          '      for (_i = 0; _i < in->%s.size; _i++) {' % fname,
          '        if (urbi_list_append(vm, _lst, %s(in->%s.data[_i])) != 0) return -1; }' % (MAKE[elem], fname),
          '      if (urbi_slot_set(vm, obj, "%s", %d, _lst) != 0) return -1; }' % (fname, flen),
        ]
    if ftype in PRIM_C:
        return ['    if (urbi_slot_set(vm, obj, "%s", %d, %s(in->%s)) != 0) return -1;' % (fname, flen, MAKE[ftype], fname)]
    nfn = "urbi_ros_unmarshal_rcl__" + ftype.replace("/", "__")
    return [
      '    { UValue _nv = urbi_make_nil();',
      '      if (%s(vm, &in->%s, &_nv) != 0) return -1;' % (nfn, fname),
      '      if (urbi_slot_set(vm, obj, "%s", %d, _nv) != 0) return -1; }' % (fname, flen),
    ]

def emit_rcl_forward(msgs):
    out = []
    for name in toposort(msgs):
        _, _, _, struct, _ = rcl_parts(name); base = name.replace("/", "__")
        out.append("int urbi_ros_marshal_rcl__%s(struct UVM *vm, UValue obj, %s *out);" % (base, struct))
        out.append("int urbi_ros_unmarshal_rcl__%s(struct UVM *vm, const %s *in, UValue *out);" % (base, struct))
    return "\n".join(out)

def emit_rcl_marshal(msgs):
    out = []
    for name in toposort(msgs):
        _, _, _, struct, _ = rcl_parts(name)
        out.append("int urbi_ros_marshal_rcl__%s(struct UVM *vm, UValue obj, %s *out) {" % (name.replace("/", "__"), struct))
        out.append("    (void)vm; (void)obj; (void)out;")
        for fname, ftype in msgs[name]:
            out += emit_rcl_marshal_field(fname, ftype)
        out.append("    return 0;\n}")
    return "\n".join(out)

def emit_rcl_unmarshal(msgs):
    out = []
    for name in toposort(msgs):
        _, _, _, struct, _ = rcl_parts(name)
        out.append("int urbi_ros_unmarshal_rcl__%s(struct UVM *vm, const %s *in, UValue *out) {" % (name.replace("/", "__"), struct))
        out.append('    struct UObject *o = urbi_ros_msg_alloc(vm, "%s");' % name)
        out.append("    if (o == NULL) return -1;")
        out.append("    UValue obj = urbi_make_object(o);")
        out.append("    (void)in;")
        for fname, ftype in msgs[name]:
            out += emit_rcl_unmarshal_field(fname, ftype)
        out.append("    *out = obj; return 0;\n}")
    return "\n".join(out)

def emit_rcl_registry(msgs):
    out = []
    all_types = toposort(msgs)
    msg_types = [n for n in all_types if not is_srv_part(n.split("/")[1])]
    for name in all_types:
        base = name.replace("/", "__"); _, _, _, struct, _ = rcl_parts(name)
        out.append("static void _ini_%s(void *p){ %s__init((%s*)p); }" % (base, struct, struct))
        out.append("static void _fin_%s(void *p){ %s__fini((%s*)p); }" % (base, struct, struct))
        out.append("static int _mr_%s(struct UVM *vm, UValue o, void *p){ return urbi_ros_marshal_rcl__%s(vm,o,(%s*)p); }" % (base, base, struct))
        out.append("static int _ur_%s(struct UVM *vm, const void *p, UValue *o){ return urbi_ros_unmarshal_rcl__%s(vm,(const %s*)p,o); }" % (base, base, struct))
    for name in msg_types:
        pkg, typ, _, _, _ = rcl_parts(name); base = name.replace("/", "__")
        out.append("static const rosidl_message_type_support_t *_ts_%s(void){ return ROSIDL_GET_MSG_TYPE_SUPPORT(%s, msg, %s); }" % (base, pkg, typ))
    out.append("static const URosRclMsgType g_rcl_msg_types[] = {")
    for name in msg_types:
        base = name.replace("/", "__"); _, _, _, struct, _ = rcl_parts(name)
        out.append('  { "%s", sizeof(%s), _ini_%s, _fin_%s, _ts_%s, _mr_%s, _ur_%s },' % (name, struct, base, base, base, base, base))
    out.append("};")
    out.append("static const int g_rcl_msg_types_n = %d;" % len(msg_types))
    out.append("const URosRclMsgType *urbi_ros_rcl_msg_lookup(const char *name){")
    out.append("  int i; for (i=0;i<g_rcl_msg_types_n;i++) if (urbi_streq(name, g_rcl_msg_types[i].name)) return &g_rcl_msg_types[i];")
    out.append("  return 0;\n}")
    # service registry: group _Request/_Response by base service name
    svc = {}
    for name in all_types:
        pkg, typ = name.split("/")
        if not is_srv_part(typ): continue
        svcname = "%s/%s" % (pkg, typ.rsplit("_", 1)[0])
        d = svc.setdefault(svcname, {})
        d["req" if typ.endswith("_Request") else "resp"] = name
    svc_list = [s for s in svc if "req" in svc[s] and "resp" in svc[s]]
    for svcname in svc_list:
        pkg, base = svcname.split("/")
        out.append("static const rosidl_service_type_support_t *_sts_%s__%s(void){ return ROSIDL_GET_SRV_TYPE_SUPPORT(%s, srv, %s); }" % (pkg, base, pkg, base))
    out.append("static const URosRclSrvType g_rcl_srv_types[] = {")
    for svcname in svc_list:
        pkg, base = svcname.split("/")
        req = svc[svcname]["req"]; resp = svc[svcname]["resp"]
        rb = req.replace("/", "__"); sb = resp.replace("/", "__")
        _, _, _, rstruct, _ = rcl_parts(req); _, _, _, sstruct, _ = rcl_parts(resp)
        out.append('  { "%s", _sts_%s__%s, sizeof(%s), sizeof(%s), _ini_%s, _fin_%s, _ini_%s, _fin_%s, _mr_%s, _ur_%s, _mr_%s, _ur_%s },' % (
            svcname, pkg, base, rstruct, sstruct, rb, rb, sb, sb, rb, rb, sb, sb))
    out.append("};")
    out.append("static const int g_rcl_srv_types_n = %d;" % len(svc_list))
    out.append("const URosRclSrvType *urbi_ros_rcl_srv_lookup(const char *name){")
    out.append("  int i; for (i=0;i<g_rcl_srv_types_n;i++) if (urbi_streq(name, g_rcl_srv_types[i].name)) return &g_rcl_srv_types[i];")
    out.append("  return 0;\n}")
    return "\n".join(out)

def emit_rcl_header(msgs):
    out = ["/* GENERATED by tools/urbi-rosgen.py --target rcl - do not edit. */",
           "#ifndef UROS_MSGS_RCL_GEN_H", "#define UROS_MSGS_RCL_GEN_H",
           "#if defined(URBI_ENABLE_ROS2) && defined(URBI_ROS_BACKEND_RCL)",
           "#include <stddef.h>", "#include <stdint.h>",
           '#include "urbi/types.h"',
           "#include <rosidl_runtime_c/message_type_support_struct.h>",
           "#include <rosidl_runtime_c/service_type_support_struct.h>",
           "", "struct UVM;", "",
           "typedef struct {",
           "    const char *name; size_t c_size;",
           "    void (*init)(void *); void (*fini)(void *);",
           "    const rosidl_message_type_support_t *(*ts)(void);",
           "    int (*marshal)(struct UVM *, UValue, void *);",
           "    int (*unmarshal)(struct UVM *, const void *, UValue *);",
           "} URosRclMsgType;",
           "const URosRclMsgType *urbi_ros_rcl_msg_lookup(const char *name);",
           "",
           "typedef struct {",
           "    const char *name;",
           "    const rosidl_service_type_support_t *(*ts)(void);",
           "    size_t req_size, resp_size;",
           "    void (*req_init)(void *); void (*req_fini)(void *);",
           "    void (*resp_init)(void *); void (*resp_fini)(void *);",
           "    int (*marshal_req)(struct UVM *, UValue, void *);",
           "    int (*unmarshal_req)(struct UVM *, const void *, UValue *);",
           "    int (*marshal_resp)(struct UVM *, UValue, void *);",
           "    int (*unmarshal_resp)(struct UVM *, const void *, UValue *);",
           "} URosRclSrvType;",
           "const URosRclSrvType *urbi_ros_rcl_srv_lookup(const char *name);",
           "#endif", "#endif", ""]
    return "\n".join(out)

def emit_rcl_c(msgs):
    headers = []
    for name in toposort(msgs):
        _, _, _, _, h = rcl_parts(name)
        if h not in headers: headers.append(h)
    parts = ["/* GENERATED by tools/urbi-rosgen.py --target rcl - do not edit. */",
             "#if defined(URBI_ENABLE_ROS2) && defined(URBI_ROS_BACKEND_RCL)",
             '#include "urbi/urbi.h"',
             '#include "urbi/types.h"',
             '#include "object/uobject.h"',
             '#include "ros/uros_msg.h"',
             '#include "ros/generated/ros_msgs_rcl.gen.h"',
             '#include "value/ulist_build.h"',
             "#include <rosidl_runtime_c/string.h>",
             "#include <rosidl_runtime_c/string_functions.h>",
             "#include <rosidl_runtime_c/primitives_sequence.h>",
             "#include <rosidl_runtime_c/primitives_sequence_functions.h>"]
    for h in headers:
        parts.append("#include <%s>" % h)
    parts += ["",
              "/* Forward declarations (nested marshal/unmarshal called in toposort order). */",
              emit_rcl_forward(msgs), "",
              emit_rcl_marshal(msgs), "",
              emit_rcl_unmarshal(msgs), "",
              emit_rcl_registry(msgs), "",
              "#else",
              "typedef int uros_rcl_gen_translation_unit_not_empty;",
              "#endif /* URBI_ENABLE_ROS2 && URBI_ROS_BACKEND_RCL */", ""]
    return "\n".join(parts)

def main():
    args = sys.argv[1:]
    target = "mock"
    if args and args[0] == "--target":
        target = args[1]; args = args[2:]
    manifest, out_c, out_h = args[0], args[1], args[2]
    msgs = json.load(open(manifest))["messages"]
    if target == "rcl":
        open(out_h, "w").write(emit_rcl_header(msgs))
        open(out_c, "w").write(emit_rcl_c(msgs))
    else:
        open(out_h, "w").write(emit_header(msgs))
        open(out_c, "w").write(emit_c(msgs))

if __name__ == "__main__":
    main()
