#!/usr/bin/env python3
"""urbi-rosgen.py — emit self-contained C structs + marshal/unmarshal + a
type registry for a fixed message manifest. v0.12.0: scalar + nested-scalar.
Usage: urbi-rosgen.py <manifest.json> <out.gen.c> <out.gen.h>"""
import json, sys

PRIM_C = {"bool": "uint8_t", "int32": "int32_t", "int64": "int64_t",
          "float32": "float", "float64": "double"}

def cident(type_name):
    return "urbi_ros__" + type_name.replace("/", "__")

def field_ctype(ftype):
    if ftype in PRIM_C:
        return PRIM_C[ftype]
    return "struct " + cident(ftype)   # nested message

def toposort(msgs):
    seen, order = set(), []
    def visit(n):
        if n in seen or n not in msgs: return
        for _, ft in msgs[n]:
            if ft not in PRIM_C: visit(ft)
        seen.add(n); order.append(n)
    for n in msgs: visit(n)
    return order

def emit_header(msgs):
    out = ["/* GENERATED by tools/urbi-rosgen.py - do not edit. */",
           "#ifndef UROS_MSGS_GEN_H", "#define UROS_MSGS_GEN_H",
           "#ifdef URBI_ENABLE_ROS2", "#include <stdint.h>", ""]
    for name in toposort(msgs):
        out.append("struct %s {" % cident(name))
        for fname, ftype in msgs[name]:
            out.append("    %s %s;" % (field_ctype(ftype), fname))
        out.append("};")
        out.append("")
    out += ["#endif", "#endif", ""]
    return "\n".join(out)

def main():
    manifest, out_c, out_h = sys.argv[1], sys.argv[2], sys.argv[3]
    msgs = json.load(open(manifest))["messages"]
    open(out_h, "w").write(emit_header(msgs))
    open(out_c, "w").write(
        '/* GENERATED - see later tasks */\n#ifdef URBI_ENABLE_ROS2\n'
        '#include "ros/generated/ros_msgs.gen.h"\n#endif\n')

if __name__ == "__main__":
    main()
