/* SPDX-License-Identifier: BSD-3-Clause */
/* tools/urbi-compile-stdlib.c
 *
 * Build-time tool: walk STDLIB_ORDER.txt, concatenate each .u source in
 * declared order, compile the joined buffer once via urbi_compile_source,
 * emit src/stdlib/urbi_stdlib_bytecode.gen.c with the resulting v1.5
 * wire-format bytecode.
 *
 * Two-pass build (per delta spec §3.1):
 *   1. liburbi.a builds with placeholder .gen.c (0-length blob)
 *   2. tools/urbi-compile-stdlib runs against that intermediate library
 *   3. liburbi.a re-links with the populated .gen.c
 *
 * Why concatenate-then-compile-once instead of one-module-per-file:
 * urbi_stdlib_boot deserializes a single UModule from the blob (see
 * src/stdlib/stdlib_boot.c §M6 Phase 4).  Multi-module loading would
 * need a length-prefixed framing format and a boot-side loop; the
 * one-module-shared-scope form keeps the boot path simple and matches
 * the way the legacy share/urbi *.u files compose anyway.  The trade-off
 * is that all overlays share one global scope at boot, which is the
 * intended semantic for stdlib content.
 *
 * Phase 3 baseline: walked the order file but produced an empty blob
 * (no urbi_compile_source).  Phase 10 closes that gap. */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "urbi/urbi.h"
#include "urbi/types.h"

/* The bake tool needs to stack-allocate a UVM, which is opaque in the
 * public API.  Pulling in the internal header here is acceptable for a
 * build-time host tool (mirrors what tools/urbi.c already does). */
#include "vm/uvm.h"

#define MAX_LINE        256
#define MAX_SOURCE      (1024 * 1024)  /* 1 MiB cap on combined .u sources */

/* Emit the .gen.c file: header comment, byte array, length variable.
 * Output format must be byte-stable for the determinism smoke gate
 * (tests/scripts/bake_smoke.sh): no timestamps, no input-path strings,
 * no PID-derived markers. */
static void
emit_c_array(FILE *out, const unsigned char *blob, size_t blob_len)
{
    fprintf(out,
        "/* AUTO-GENERATED by tools/urbi-compile-stdlib. Do not edit.\n"
        " *\n"
        " * Build-time output: walks src/stdlib/STDLIB_ORDER.txt, compiles\n"
        " * each .u to bytecode via the public compile API, concatenates the\n"
        " * resulting v1.5 wire-format buffers, emits this file.\n"
        " *\n"
        " * Empty placeholder until Phase 10 populates STDLIB_ORDER.txt.\n"
        " */\n"
        "\n"
        "#include <stddef.h>\n"
        "\n"
        "const unsigned char urbi_stdlib_bytecode[%zu] = {\n",
        blob_len ? blob_len : (size_t)1);

    if (blob_len == 0) {
        fprintf(out, "    0\n");
    } else {
        for (size_t i = 0; i < blob_len; i++) {
            if (i % 16 == 0) fprintf(out, "    ");
            fprintf(out, "0x%02X,", blob[i]);
            if ((i + 1) % 16 == 0 || i + 1 == blob_len) {
                fprintf(out, "\n");
            } else {
                fprintf(out, " ");
            }
        }
    }
    fprintf(out,
        "};\n"
        "\n"
        "const size_t urbi_stdlib_bytecode_len = %zu;\n",
        blob_len);
}

/* Append the contents of `path` to (*src, *len), growing the heap buffer.
 * Returns 0 on success, non-zero on failure (message to stderr). */
static int
append_source_file(const char *path, char **src, size_t *len, size_t *cap)
{
    FILE *fp = fopen(path, "rb");
    if (!fp) {
        fprintf(stderr, "[bake] cannot open %s\n", path);
        return 1;
    }
    /* File-scope banner so concat boundaries appear in compile diagnostics. */
    char banner[512];
    int blen = snprintf(banner, sizeof banner,
                        "// === %s ===\n", path);
    if (blen < 0) blen = 0;

    /* Reserve banner bytes first. */
    while (*len + (size_t)blen + 1 > *cap) {
        size_t ncap = *cap ? *cap * 2 : 8192;
        if (ncap > MAX_SOURCE) {
            fclose(fp);
            fprintf(stderr, "[bake] combined sources exceed %u byte cap\n",
                    (unsigned)MAX_SOURCE);
            return 1;
        }
        char *nb = realloc(*src, ncap);
        if (!nb) { fclose(fp); fprintf(stderr, "[bake] OOM\n"); return 1; }
        *src = nb;
        *cap = ncap;
    }
    memcpy(*src + *len, banner, (size_t)blen);
    *len += (size_t)blen;

    /* Append file body. */
    for (;;) {
        if (*len + 4096 + 2 > *cap) {
            size_t ncap = *cap * 2;
            if (ncap > MAX_SOURCE) {
                fclose(fp);
                fprintf(stderr, "[bake] combined sources exceed %u byte cap\n",
                        (unsigned)MAX_SOURCE);
                return 1;
            }
            char *nb = realloc(*src, ncap);
            if (!nb) {
                fclose(fp);
                fprintf(stderr, "[bake] OOM\n");
                return 1;
            }
            *src = nb;
            *cap = ncap;
        }
        size_t r = fread(*src + *len, 1, 4096, fp);
        *len += r;
        if (r == 0) break;
    }
    fclose(fp);

    /* Trailing newline guards against a final source missing a newline
     * before the next file's banner.  Two newlines so any unterminated
     * trailing comment / pipe sees a clean separator. */
    if (*len + 2 > *cap) {
        size_t ncap = *cap * 2;
        char *nb = realloc(*src, ncap);
        if (!nb) { fprintf(stderr, "[bake] OOM\n"); return 1; }
        *src = nb;
        *cap = ncap;
    }
    (*src)[(*len)++] = '\n';
    (*src)[(*len)++] = '\n';
    return 0;
}

int
main(int argc, char **argv)
{
    if (argc != 4) {
        fprintf(stderr,
            "usage: %s STDLIB_ORDER.txt SRC_DIR OUTPUT.gen.c\n",
            argv[0]);
        return 2;
    }
    const char *order_path = argv[1];
    const char *src_dir    = argv[2];
    const char *out_path   = argv[3];

    FILE *order = fopen(order_path, "r");
    if (!order) {
        fprintf(stderr, "[bake] cannot open %s\n", order_path);
        return 1;
    }

    char  *combined = NULL;
    size_t comb_len = 0;
    size_t comb_cap = 0;
    int    n_files  = 0;

    char line[MAX_LINE];
    while (fgets(line, sizeof line, order)) {
        size_t n = strlen(line);
        while (n && (line[n - 1] == '\n' || line[n - 1] == '\r')) {
            line[--n] = 0;
        }
        if (n == 0) continue;            /* blank line */
        if (line[0] == '#') continue;    /* comment */

        /* Build SRC_DIR/<basename>. */
        char path[MAX_LINE * 2];
        snprintf(path, sizeof path, "%s/%s", src_dir, line);

        if (append_source_file(path, &combined, &comb_len, &comb_cap) != 0) {
            free(combined);
            fclose(order);
            return 1;
        }
        n_files++;
    }
    fclose(order);

    /* Compile the combined source.  Empty blob if STDLIB_ORDER.txt is
     * empty — preserves Phase 4 baseline behavior. */
    unsigned char *bc      = NULL;
    size_t         bc_len  = 0;

    if (comb_len > 0) {
        UVM vm;
        urbi_vm_init(&vm, NULL, NULL);

        char err[512] = {0};
        int rc = urbi_compile_source(&vm, combined, comb_len, "stdlib",
                                     &bc, &bc_len, err, sizeof err);
        urbi_vm_destroy(&vm);

        if (rc != URBI_OK) {
            fprintf(stderr, "[bake] compile failed: %s\n",
                    err[0] ? err : "(no diagnostic)");
            free(combined);
            return 1;
        }
    }
    free(combined);

    FILE *out = fopen(out_path, "w");
    if (!out) {
        free(bc);
        fprintf(stderr, "[bake] cannot open %s for writing\n", out_path);
        return 1;
    }
    emit_c_array(out, bc, bc_len);
    fclose(out);
    free(bc);

    fprintf(stderr, "[bake] wrote %s (%d file(s), %zu bytes blob)\n",
            out_path, n_files, bc_len);
    return 0;
}
